# -*- coding: utf-8 -*-
"""Gaussian_nive_bayes_on_wetherAus .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIWogmSqHZLmEn4FH8T65G6a6O9JCKOV
"""

import pandas as pd
import numpy as np

import pandas as pd
data=pd.read_csv('/content/weatherAUS.csv')
data.head()

data.isnull().sum()

for col in data.columns:
  if data[col].dtypes == 'object':
    data[col].fillna(data[col].mode()[0], inplace=True)
  else:
    data[col].fillna(data[col].median(), inplace=True)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in data.columns:
  if data[col].dtypes=='object':
    data[col]=le.fit_transform(data[col])

data

from sklearn.model_selection import train_test_split
x=data.drop(['RainTomorrow', 'Date'], axis=1)
y=data['RainTomorrow']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

data.info()



from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)